const formulas = [
    { id: 1, name: "Circle Equation", math: "(x-h)^2 + (y-k)^2 \\\\ = r^2", gift: "Save 90s", link: "#f1" },
    { id: 2, name: "Vertex Shortcut", math: "x = \\frac{-b}{2a}", gift: "Save 70s", link: "#f2" },
    { id: 3, name: "Product of Solutions", math: "\\frac{c}{a}", gift: "Save 65s", link: "#f3" },
    { id: 4, name: "Sum of Solutions", math: "\\frac{-b}{a}", gift: "Save 50s", link: "#f4" },
    { id: 5, name: "Complementary Trig", math: "\\sin(x) = \\\\ \\cos(90^\\circ - x)", gift: "Instant pts", link: "#f5" },
    { id: 6, name: "Exterior Angle Sum", math: "360^\\circ", gift: "Instant pts", link: "#f6" },
    { id: 7, name: "The Discriminant", math: "b^2 - 4ac", gift: "Fast logic", link: "#f7" },
    { id: 8, name: "Weighted Average", math: "\\frac{\\sum (w \\cdot x)}{\\sum w}", gift: "Speed mixtures", link: "#f8" },
    { id: 9, name: "Harmonic Mean", math: "\\frac{2ab}{a+b}", gift: "Avg Speed hack", link: "#f9" },
    { id: 10, name: "Distance from Origin", math: "\\sqrt{x^2 + y^2}", gift: "Speed Pythag", link: "#f10" },
    { id: 11, name: "Growth & Decay", math: "a(1 \\pm r)^t", gift: "No manual %", link: "#f11" },
    { id: 12, name: "Percent Change", math: "\\frac{N - O}{O} \\\\ \\times 100", gift: "No confusion", link: "#f12" },
    { id: 13, name: "Arc Area (Proportion)", math: "\\frac{Area}{\\pi r^2} = \\\\ \\frac{\\theta}{360^\\circ}", gift: "No formulas", link: "#f13" },
    { id: 14, name: "The 'Golden' Ratio Pattern", math: "1 : \\sqrt{3} : 2", gift: "Triangle Hack", link: "#f14" },
    { id: 15, name: "Slope Formula", math: "m = \\frac{y_2 - y_1}{x_2 - x_1}", gift: "Basic", link: "#f15" },
    { id: 16, name: "Parallel Slopes", math: "m_1 = m_2", gift: "Basic", link: "#f16" },
    { id: 17, name: "Perpendicular Slopes", math: "m_1 \\cdot m_2 = -1", gift: "Basic", link: "#f17" },
    { id: 18, name: "Standard Deviation Logic", math: "\\text{High Spread} = \\\\ \\text{High } \\sigma", gift: "Stat Mastery", link: "#f18" },
    { id: 19, name: "Margin of Error", math: "n \\uparrow \\; \\Rightarrow \\; MoE \\downarrow", gift: "Stat Mastery", link: "#f19" },
    { id: 20, name: "Sum of Interior Angles", math: "(n-2) \\cdot 180^\\circ", gift: "Polygons", link: "#f20" },
    { id: 21, name: "Equation of Circle (General)", math: "x^2 + y^2 + Dx \\\\ + Ey + F = 0", gift: "Mental Math", link: "#f21" }
];
